[terminal.shell]
program = "pwsh.exe"

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font]
size = 12.0

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
